POST https://api.edu.cdek.ru/v2/oauth/token?parameters
content-type: application/x-www-form-urlencoded

{
     "grant-type": "client_credentials",
     "client_id": "EMscd6r9JnFiQ3bLoyjJY6eM78JrJceI",
     "client_secret": "PjLZkKBHEiLK3YsjtNrt3TGNG0ahs3kG"
}